name: first-workflow
on: push
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm test
      - name: deploy
        run: npm run build

  job-two:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint

  job-three:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: install dependencies
        run: npm ci
      - name: test
        run: npm test

  job-four:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: install dependencies
        run: npm ci
      - name: deploy
        run: npm run build